package Recursion;

import java.util.ArrayList;
import java.util.Scanner;

//Given a String. WAP to return all its subsequences in an arrayList. A String is a subsequences of a given String that is generated by deleting some characters of a given string without changing its order.
//Input: abc
//Output:  ,a,b,c,ab,bc,ac,abc
public class returnSubsequence {
    static ArrayList<String> getSSQ(String s){
        ArrayList<String> ans = new ArrayList<>();
        //base case
        if(s.length()==0){
            ans.add("");
            return ans;
        }
        //recursive work
        char currChar = s.charAt(0);
        ArrayList<String> smallAns = getSSQ(s.substring(1));
        for(String ss:smallAns){
            ans.add(ss);
            ans.add(currChar+ss);
        }
        return ans;
    }
    public static void main(String[] args) {
        Scanner sc = new Scanner(System.in);
        System.out.print("Enter string: ");
        String s = sc.nextLine();
        ArrayList<String> ans = getSSQ(s);
        for(String ss:ans){
            System.out.print(ss+" ");
        }
    }
}
