package DynamicProgramming;
/*
Given two strings, S1 and S2, the task is to find the length of the longest subsequence present in both of the strings.
A subsequence of a string is a sequence that is generated by deleting some characters(possibly 0) from the string without altering the order of the
remaining characters. For example, "abc","abg","bdf","aeg","acefg",etc are subsequences of the string "abcdefg".
 */
public class longestCommonSubsequence {
    public static void main(String[] args) {

    }
}
